development:
  adapter: postgresql
  encoding: unicode
  database: url_shortner
  pool: 5
  username: postgres
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: url_shortner
  pool: 5
  username: postgres
  password:

